<?php

namespace App\Http\Requests\Transaction\Concerns;

use App\Services\Accounting\TransactionService;

/**
 * The client's own name for the document it is creating — M17, and the brief's
 * §28.
 *
 * Shared by every store request rather than written five times, because the
 * field means exactly one thing wherever it appears and five copies of a rule
 * is four opportunities for one of them to drift.
 *
 * A UUID, generated by the client **once**, when the operator starts writing the
 * document — not per request. That is the whole mechanism: a value regenerated
 * on retry would make the second attempt look like a different bill, which is
 * precisely the outcome it exists to prevent.
 *
 * Optional, so a `curl` against the API still works and so every server-side
 * caller — M11's importer, a seeder — can leave it off. What it costs to leave
 * off is the protection; see {@see TransactionService::create()}.
 */
trait CarriesClientRef
{
    /**
     * @return array<string, mixed>
     */
    protected function clientRefRules(): array
    {
        return [
            // A UUID rather than a free string, so a client cannot accidentally
            // send something that collides — "bill-1" would be a very effective
            // way of never being able to write a second bill.
            'client_ref' => ['sometimes', 'nullable', 'uuid'],
        ];
    }

    /**
     * Public because the return route hands it to a service rather than folding
     * it into a compose payload — see `TransactionController::storeReturn()`.
     */
    public function clientRef(): ?string
    {
        return $this->filled('client_ref') ? (string) $this->input('client_ref') : null;
    }
}
